#!/bin/bash
#AZZATSSINS
#Linux Hacking Tools
#Thx to Mehedi Shakeel for Recomendation
clear
git clone https://github.com/DanMcInerney/shellshock-hunter
git clone https://github.com/DanMcInerney/shellshock-hunter-google
git clone https://github.com/DanMcInerney/wifijammer
git clone https://github.com/darkoperator/dnsrecon
git clone https://github.com/ddos-defense/bohatei
git clone https://github.com/desaster/kippo
git clone https://github.com/devttys0/binwalk
git clone https://github.com/digininja/CeWL
git clone https://github.com/Dionach/CMSmap
git clone https://github.com/dloss/python-pentest-tools
git clone https://github.com/DoddyHackman/Arsenal_X
git clone https://github.com/DominikSchlecht/pyDirBuster
git clone https://github.com/dotfighter/torshammer
git clone https://github.com/dripcap/dripcap
git clone https://github.com/EgeBalci/The-Eye
git clone https://github.com/EnableSecurity/wafw00f
git clone https://github.com/endgameinc/binarypig
git clone https://github.com/epinna/weevely3
git clone https://github.com/Ettercap/ettercap
git clone https://github.com/evilsocket/bettercap
git clone https://github.com/ex0dus-0x/brut3k1t
git clone https://github.com/ex0dus-0x/dedsploit
git clone https://github.com/fgeek/pyfiscan
git clone https://github.com/foospidy/HoneyPy
git clone https://github.com/frdmn/findmyhash
git clone https://github.com/g0tmi1k/mpc
git clone https://github.com/gabrielrcouto/reaver-wps
git clone https://github.com/mempodippy/vlany.git
git clone https://github.com/unix-thrust/beurk.git
git clone https://github.com/nmap/nmap.git
git clone https://github.com/leviathan-framework/leviathan.git
git clone https://github.com/n1nj4sec/pupy/tree/master/client
git clone https://github.com/valyala/goloris.git
git clone https://github.com/radare/radare2.git
git clone https://github.com/OffensivePython/Saddam.git
git clone https://github.com/botherder/virustotal.git
git clone https://github.com/Microsoft/binskim.git
git clone https://github.com/0xd4d/dnSpy.git
git clone https://github.com/lowleveldesign/wtrace.git
git clone https://github.com/spesmilo/electrum.git
git clone https://github.com/bitcoin-wallet/bitcoin-wallet.git
git clone https://github.com/tuxotron/xvwa_lamp_container.git
git clone https://github.com/JonathanSalwan/Triton.git
git clone https://github.com/hypsurus/weeman.git
git clone https://github.com/krmaxwell/tinfoleak
git clone https://github.com/secretsquirrel/fido.git
git clone https://github.com/gentilkiwi/mimikatz.git
git clone https://github.com/SecurityInnovation/AuthMatrix.git
git clone https://github.com/akheron/jansson
git clone https://github.com/wolf9466/cpuminer-multi.git
git clone https://github.com/tsiv/ccminer-cryptonight.git
git clone https://github.com/evilsocket/bettercap-proxy-modules.git
git clone https://github.com/Raikia/FiercePhish.git
git clone https://github.com/adaptivethreat/Empire.git
git clone https://github.com/gophish/gophish.git
git clone https://github.com/DhavalKapil/icmptunnel.git
git clone https://github.com/sqlmapproject/sqlmap.git
git clone https://github.com/davidpepper/fierce-domain-scanner.git
git clone https://github.com/Mebus/cupp.git
git clone https://github.com/digininja/CeWL.git
git clone https://github.com/iagox86/dnscat2.git
git clone https://github.com/ryhanson/phishery.git
git clone https://github.com/JusticeRage/Manalyze.git
git clone git://git.kali.org/packages/exploitdb.git
git clone https://github.com/trustedsec/social-engineer-toolkit.git
git clone https://github.com/roobixx/cowpatty.git
git clone https://github.com/hashcat/hashcat.git
git clone https://github.com/laramies/theHarvester.git
git clone https://github.com/secretsquirrel/the-backdoor-factory.git
git clone https://github.com/EnableSecurity/wafw00f.git
git clone https://github.com/stephenfewer/ReflectiveDLLInjection.git
git clone https://github.com/kstaken/dockerfile-examples.git
git clone https://github.com/xmendez/wfuzz.git
git clone https://github.com/pxb1988/dex2jar.git
git clone git://git.kali.org/packages/dirbuster.git
git clone https://github.com/deltaxflux/fluxion.git
git clone git://git.kali.org/packages/joomscan.git
git clone https://github.com/hexploitable/MEMSCAN.git
git clone https://github.com/hiddenillusion/AnalyzePDF.git
git clone https://github.com/smalot/pdfparser.git
git clone https://github.com/jesparza/peepdf.git
git clone https://github.com/reverse-shell/routersploit.git
git clone https://github.com/google/sandbox-attacksurface-analysis-tools.git
git clone https://github.com/sophron/wifiphisher.git
git clone https://github.com/wpscanteam/wpscan.git
git clone https://github.com/Yara-Rules/rules.git
git clone git://github.com/cuckoosandbox/cuckoo.git
git clone https://github.com/juansacco/exploitpack.git
git clone https://github.com/BlackArch/webshells.git
git clone https://github.com/EgeBalci/HERCULES.git
git clone https://github.com/EgeBalci/Cminer.git
git clone https://github.com/EgeBalci/The-Eye.git
git clone https://github.com/DanMcInerney/wifijamm
clear
ls
